import { Component, computed, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import * as i0 from "@angular/core";
const _c0 = () => ["A01", "A02", "CAR", "B26", "B27", "B28", "C10", "C11", "C12"];
const _forTrack0 = ($index, $item) => $item.title;
function Landing_Conditional_180_Template(rf, ctx) { if (rf & 1) {
    i0.ɵɵelementStart(0, "p", 42);
    i0.ɵɵtext(1);
    i0.ɵɵelementEnd();
} if (rf & 2) {
    const ctx_r0 = i0.ɵɵnextContext();
    i0.ɵɵadvance();
    i0.ɵɵtextInterpolate(ctx_r0.searchMessage());
} }
function Landing_For_183_Template(rf, ctx) { if (rf & 1) {
    const _r2 = i0.ɵɵgetCurrentView();
    i0.ɵɵelementStart(0, "article", 44)(1, "div", 82)(2, "span", 83)(3, "b");
    i0.ɵɵtext(4);
    i0.ɵɵelementEnd();
    i0.ɵɵtext(5);
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(6, "button", 84);
    i0.ɵɵlistener("click", function Landing_For_183_Template_button_click_6_listener() { const event_r3 = i0.ɵɵrestoreView(_r2).$implicit; const ctx_r0 = i0.ɵɵnextContext(); return i0.ɵɵresetView(ctx_r0.toggleFavorite(event_r3.title)); });
    i0.ɵɵtext(7);
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(8, "span", 85);
    i0.ɵɵtext(9);
    i0.ɵɵelementEnd()();
    i0.ɵɵelementStart(10, "div", 86)(11, "h3");
    i0.ɵɵtext(12);
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(13, "p");
    i0.ɵɵtext(14);
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(15, "p");
    i0.ɵɵtext(16);
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(17, "div")(18, "span");
    i0.ɵɵtext(19, "From ");
    i0.ɵɵelementStart(20, "strong");
    i0.ɵɵtext(21);
    i0.ɵɵelementEnd()();
    i0.ɵɵelementStart(22, "small");
    i0.ɵɵtext(23);
    i0.ɵɵelementEnd()()()();
} if (rf & 2) {
    const event_r3 = ctx.$implicit;
    const ctx_r0 = i0.ɵɵnextContext();
    i0.ɵɵadvance();
    i0.ɵɵstyleProp("background-position", event_r3.imagePosition);
    i0.ɵɵadvance(3);
    i0.ɵɵtextInterpolate(event_r3.day);
    i0.ɵɵadvance();
    i0.ɵɵtextInterpolate(event_r3.month);
    i0.ɵɵadvance();
    i0.ɵɵclassProp("saved", ctx_r0.favoriteTitles().has(event_r3.title));
    i0.ɵɵattribute("aria-label", "Save " + event_r3.title);
    i0.ɵɵadvance();
    i0.ɵɵtextInterpolate(ctx_r0.favoriteTitles().has(event_r3.title) ? "\u2665" : "\u2661");
    i0.ɵɵadvance(2);
    i0.ɵɵtextInterpolate(event_r3.category);
    i0.ɵɵadvance(3);
    i0.ɵɵtextInterpolate(event_r3.title);
    i0.ɵɵadvance(2);
    i0.ɵɵtextInterpolate1("\u2316 ", event_r3.venue);
    i0.ɵɵadvance(2);
    i0.ɵɵtextInterpolate1("\u25F7 ", event_r3.time);
    i0.ɵɵadvance(5);
    i0.ɵɵtextInterpolate(event_r3.price);
    i0.ɵɵadvance(2);
    i0.ɵɵtextInterpolate(event_r3.ticketType);
} }
function Landing_ForEmpty_184_Template(rf, ctx) { if (rf & 1) {
    i0.ɵɵelementStart(0, "div", 45);
    i0.ɵɵtext(1, "Try another search or category.");
    i0.ɵɵelementEnd();
} }
function Landing_For_264_Template(rf, ctx) { if (rf & 1) {
    i0.ɵɵelementStart(0, "button", 87);
    i0.ɵɵtext(1);
    i0.ɵɵelementStart(2, "small");
    i0.ɵɵtext(3);
    i0.ɵɵelementEnd()();
} if (rf & 2) {
    const slot_r4 = ctx.$implicit;
    i0.ɵɵclassProp("selected", slot_r4 === "B27")("busy", slot_r4 === "B28" || slot_r4 === "CAR");
    i0.ɵɵadvance();
    i0.ɵɵtextInterpolate(slot_r4 === "CAR" ? "\uD83D\uDE99" : slot_r4);
    i0.ɵɵadvance(2);
    i0.ɵɵtextInterpolate(slot_r4 === "B27" ? "\u2713" : "");
} }
export class Landing {
    menuOpen = signal(false, /* @ts-ignore */
    ...(ngDevMode ? [{ debugName: "menuOpen" }] : /* istanbul ignore next */ []));
    query = signal('', /* @ts-ignore */
    ...(ngDevMode ? [{ debugName: "query" }] : /* istanbul ignore next */ []));
    selectedCategory = signal('All Categories', /* @ts-ignore */
    ...(ngDevMode ? [{ debugName: "selectedCategory" }] : /* istanbul ignore next */ []));
    favoriteTitles = signal(new Set(), /* @ts-ignore */
    ...(ngDevMode ? [{ debugName: "favoriteTitles" }] : /* istanbul ignore next */ []));
    searchMessage = signal('', /* @ts-ignore */
    ...(ngDevMode ? [{ debugName: "searchMessage" }] : /* istanbul ignore next */ []));
    events = [
        { day: '24', month: 'MAY', category: 'Concert', title: 'AR Rahman Live in Chennai', venue: 'Jawaharlal Nehru Stadium, Chennai', time: '7:00 PM', price: '₹1,500', ticketType: 'Seat Based', imagePosition: '0% 34%' },
        { day: '10', month: 'JUN', category: 'Sports', title: 'IPL Finals 2025', venue: 'M.A. Chidambaram Stadium, Chennai', time: '7:30 PM', price: '₹2,000', ticketType: 'Seat Based', imagePosition: '33.333% 48%' },
        { day: '15', month: 'JUL', category: 'Conference', title: 'Tech Summit 2026', venue: 'Chennai Trade Centre, Chennai', time: '10:00 AM', price: '₹999', ticketType: 'Non-Seat Based', imagePosition: '66.666% 45%' },
        { day: '28', month: 'AUG', category: 'Festival', title: 'Chennai Food Carnival', venue: 'Island Grounds, Chennai', time: '4:00 PM', price: '₹299', ticketType: 'Non-Seat Based', imagePosition: '100% 55%' },
    ];
    filteredEvents = computed(() => {
        const query = this.query().trim().toLowerCase();
        const category = this.selectedCategory();
        return this.events.filter((event) => {
            const matchesQuery = !query || `${event.title} ${event.venue} ${event.category}`.toLowerCase().includes(query);
            const matchesCategory = category === 'All Categories' || event.category === category;
            return matchesQuery && matchesCategory;
        });
    }, /* @ts-ignore */
    ...(ngDevMode ? [{ debugName: "filteredEvents" }] : /* istanbul ignore next */ []));
    updateQuery(event) {
        this.query.set(event.target.value);
        this.searchMessage.set('');
    }
    updateCategory(event) {
        this.selectedCategory.set(event.target.value);
        this.searchMessage.set('');
    }
    findEvents() {
        const count = this.filteredEvents().length;
        this.searchMessage.set(count ? `${count} matching event${count === 1 ? '' : 's'} found.` : 'No matching events found.');
        document.querySelector('#events')?.scrollIntoView({ behavior: 'smooth' });
    }
    toggleFavorite(title) {
        const next = new Set(this.favoriteTitles());
        next.has(title) ? next.delete(title) : next.add(title);
        this.favoriteTitles.set(next);
    }
    static ɵfac = function Landing_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || Landing)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: Landing, selectors: [["app-landing"]], decls: 428, vars: 7, consts: [["id", "home", 1, "hero"], ["aria-label", "Main navigation", 1, "nav", "shell"], ["href", "#home", "aria-label", "Eventora home", 1, "brand"], ["aria-hidden", "true", 1, "brand-mark"], ["type", "button", "aria-label", "Toggle menu", 1, "menu-toggle", 3, "click"], [1, "nav-links"], ["href", "#home", 1, "active"], ["href", "#events"], ["href", "#how"], ["href", "#parking"], ["href", "#roles"], ["href", "#footer"], [1, "nav-actions"], ["type", "button", "aria-label", "Search", 1, "icon-button"], ["routerLink", "/login", 1, "btn", "btn-white"], ["type", "button", 1, "btn", "btn-primary"], [1, "hero-content", "shell"], [1, "hero-copy"], [1, "eyebrow"], [1, "hero-buttons"], ["href", "#events", 1, "btn", "btn-primary", "btn-large"], ["href", "#how", 1, "btn", "btn-outline", "btn-large"], [1, "trust-row"], ["aria-label", "Booking preview", 1, "booking-preview"], [1, "preview-card", "upcoming"], [1, "preview-icon", "pink"], [1, "preview-pair"], [1, "preview-card"], [1, "preview-icon", "violet"], [1, "preview-icon", "green"], ["aria-label", "Digital ticket preview", 1, "ticket-phone"], ["aria-hidden", "true", 1, "qr-pattern"], ["aria-label", "Find events", 1, "search-wrap", "shell"], [1, "search-grid"], [1, "search-field", "wide"], ["type", "search", "placeholder", "Search events, artists, or venues...", 3, "input", "value"], [1, "select-field"], [3, "change", "value"], ["type", "button", 1, "btn", "btn-primary", "find-btn", 3, "click"], [1, "category-row"], ["id", "events", 1, "section", "shell"], [1, "section-head"], ["role", "status", 1, "search-message"], [1, "event-grid"], [1, "event-card"], [1, "empty-state"], ["id", "how", 1, "section", "shell", "how"], [1, "steps"], [1, "step-number"], [1, "step-icon"], [1, "step-icon", "pink"], [1, "step-icon", "green"], [1, "step-icon", "blue"], ["id", "parking", 1, "parking-feature", "shell"], [1, "parking-photo"], [1, "parking-copy"], [1, "smart-pill"], ["href", "#how", 1, "btn", "btn-primary"], [1, "parking-map"], ["type", "button", 3, "selected", "busy"], [1, "parking-legend"], ["id", "roles", 1, "section", "shell", "roles"], [1, "role-grid"], [1, "featured"], [1, "role-icon"], [1, "btn", "btn-primary"], [1, "role-icon", "pink"], [1, "btn", "btn-soft"], [1, "role-icon", "blue"], [1, "stats", "shell"], [1, "final-cta", "shell"], ["href", "#events", 1, "btn", "btn-white"], ["type", "button", 1, "btn", "btn-outline"], ["id", "footer"], [1, "footer-grid", "shell"], ["href", "#home", 1, "brand"], [1, "brand-mark"], [1, "socials"], ["routerLink", "/login"], ["href", "#home"], [1, "footer-bottom", "shell"], ["href", "#home", "aria-label", "Back to top", 1, "back-top"], [1, "event-image"], [1, "date-badge"], ["type", "button", 1, "heart", 3, "click"], [1, "category-badge"], [1, "event-body"], ["type", "button"]], template: function Landing_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵelementStart(0, "header", 0)(1, "nav", 1)(2, "a", 2)(3, "span", 3);
            i0.ɵɵtext(4, "\u2726");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(5, "span")(6, "strong");
            i0.ɵɵtext(7, "Eventora");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(8, "small");
            i0.ɵɵtext(9, "Events \u2022 Tickets \u2022 Parking");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(10, "button", 4);
            i0.ɵɵlistener("click", function Landing_Template_button_click_10_listener() { return ctx.menuOpen.set(!ctx.menuOpen()); });
            i0.ɵɵtext(11, "\u2630");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(12, "div", 5)(13, "a", 6);
            i0.ɵɵtext(14, "Home");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(15, "a", 7);
            i0.ɵɵtext(16, "Events");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(17, "a", 8);
            i0.ɵɵtext(18, "How It Works");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(19, "a", 9);
            i0.ɵɵtext(20, "Parking");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(21, "a", 10);
            i0.ɵɵtext(22, "About");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(23, "a", 11);
            i0.ɵɵtext(24, "Contact");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(25, "div", 12)(26, "button", 13);
            i0.ɵɵtext(27, "\u2315");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(28, "a", 14);
            i0.ɵɵtext(29, "Log In");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(30, "button", 15);
            i0.ɵɵtext(31, "Create Account");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(32, "div", 16)(33, "div", 17)(34, "span", 18);
            i0.ɵɵtext(35, "Events \u2022 Tickets \u2022 Parking \u2014 All in One Place");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(36, "h1");
            i0.ɵɵtext(37, "Book the Event.");
            i0.ɵɵelement(38, "br");
            i0.ɵɵtext(39, "Reserve Your Seat.");
            i0.ɵɵelement(40, "br");
            i0.ɵɵelementStart(41, "em");
            i0.ɵɵtext(42, "Park Without Stress.");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(43, "p");
            i0.ɵɵtext(44, "Discover events, choose your perfect seat, reserve parking, and manage everything from one seamless experience.");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(45, "div", 19)(46, "a", 20);
            i0.ɵɵtext(47, "Explore Events ");
            i0.ɵɵelementStart(48, "span");
            i0.ɵɵtext(49, "\u2192");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(50, "a", 21);
            i0.ɵɵtext(51, "Get Started");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(52, "div", 22)(53, "span");
            i0.ɵɵtext(54, "\u25CF Secure Booking");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(55, "span");
            i0.ɵɵtext(56, "\u25CF Easy & Fast");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(57, "span");
            i0.ɵɵtext(58, "\u25CF Parking is Optional");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(59, "div", 23)(60, "article", 24)(61, "span", 25);
            i0.ɵɵtext(62, "\u266B");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(63, "div")(64, "small");
            i0.ɵɵtext(65, "Upcoming Event");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(66, "strong");
            i0.ɵɵtext(67, "Summer Music Fest");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(68, "span");
            i0.ɵɵtext(69, "\u25F7 May 24, 2025 \u2022 6:00 PM");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(70, "span");
            i0.ɵɵtext(71, "\u2316 Chennai Stadium");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(72, "b");
            i0.ɵɵtext(73, "\u2192");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(74, "div", 26)(75, "article", 27)(76, "span", 28);
            i0.ɵɵtext(77, "\u2726");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(78, "div")(79, "small");
            i0.ɵɵtext(80, "Your Tickets");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(81, "strong");
            i0.ɵɵtext(82, "A1, A2");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(83, "i");
            i0.ɵɵtext(84, "Confirmed");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(85, "article", 27)(86, "span", 29);
            i0.ɵɵtext(87, "P");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(88, "div")(89, "small");
            i0.ɵɵtext(90, "Parking Slot");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(91, "strong");
            i0.ɵɵtext(92, "Zone B \u2022 B27");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(93, "i");
            i0.ɵɵtext(94, "Reserved");
            i0.ɵɵelementEnd()()()()();
            i0.ɵɵelementStart(95, "div", 30)(96, "small");
            i0.ɵɵtext(97, "\u2726 Eventora");
            i0.ɵɵelementEnd();
            i0.ɵɵelement(98, "div", 31);
            i0.ɵɵelementStart(99, "strong");
            i0.ɵɵtext(100, "Your Event Ticket");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(101, "span");
            i0.ɵɵtext(102, "Scan at Entry");
            i0.ɵɵelementEnd()()()();
            i0.ɵɵelementStart(103, "main")(104, "section", 32)(105, "div", 33)(106, "label", 34)(107, "span");
            i0.ɵɵtext(108, "\u2315");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(109, "input", 35);
            i0.ɵɵlistener("input", function Landing_Template_input_input_109_listener($event) { return ctx.updateQuery($event); });
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(110, "label", 36)(111, "span");
            i0.ɵɵtext(112, "\u2316");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(113, "small");
            i0.ɵɵtext(114, "Location / Venue");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(115, "select")(116, "option");
            i0.ɵɵtext(117, "All Locations");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(118, "option");
            i0.ɵɵtext(119, "Chennai");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(120, "option");
            i0.ɵɵtext(121, "Bengaluru");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(122, "label", 36)(123, "span");
            i0.ɵɵtext(124, "\u25A6");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(125, "small");
            i0.ɵɵtext(126, "Category");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(127, "select", 37);
            i0.ɵɵlistener("change", function Landing_Template_select_change_127_listener($event) { return ctx.updateCategory($event); });
            i0.ɵɵelementStart(128, "option");
            i0.ɵɵtext(129, "All Categories");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(130, "option");
            i0.ɵɵtext(131, "Concert");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(132, "option");
            i0.ɵɵtext(133, "Sports");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(134, "option");
            i0.ɵɵtext(135, "Conference");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(136, "option");
            i0.ɵɵtext(137, "Festival");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(138, "label", 36)(139, "span");
            i0.ɵɵtext(140, "\u25A3");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(141, "small");
            i0.ɵɵtext(142, "Date");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(143, "select")(144, "option");
            i0.ɵɵtext(145, "Any Date");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(146, "option");
            i0.ɵɵtext(147, "This Week");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(148, "option");
            i0.ɵɵtext(149, "This Month");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(150, "button", 38);
            i0.ɵɵlistener("click", function Landing_Template_button_click_150_listener() { return ctx.findEvents(); });
            i0.ɵɵtext(151, "Find Events ");
            i0.ɵɵelementStart(152, "b");
            i0.ɵɵtext(153, "\u2192");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(154, "div", 39)(155, "strong");
            i0.ɵɵtext(156, "Popular Categories:");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(157, "button");
            i0.ɵɵtext(158, "\u266B Concert");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(159, "button");
            i0.ɵɵtext(160, "\uD83C\uDFC6 Sports");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(161, "button");
            i0.ɵɵtext(162, "\u265F Conference");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(163, "button");
            i0.ɵɵtext(164, "\u25A3 Workshop");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(165, "button");
            i0.ɵɵtext(166, "\u25B2 Festival");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(167, "button");
            i0.ɵɵtext(168, "\u25A6 Other");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(169, "section", 40)(170, "div", 41)(171, "div")(172, "h2");
            i0.ɵɵtext(173, "Events ");
            i0.ɵɵelementStart(174, "em");
            i0.ɵɵtext(175, "You\u2019ll Love");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(176, "p");
            i0.ɵɵtext(177, "Discover popular and upcoming experiences.");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(178, "a", 7);
            i0.ɵɵtext(179, "View All Events \u2192");
            i0.ɵɵelementEnd()();
            i0.ɵɵconditionalCreate(180, Landing_Conditional_180_Template, 2, 1, "p", 42);
            i0.ɵɵelementStart(181, "div", 43);
            i0.ɵɵrepeaterCreate(182, Landing_For_183_Template, 24, 14, "article", 44, _forTrack0, false, Landing_ForEmpty_184_Template, 2, 0, "div", 45);
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(185, "section", 46)(186, "div", 41)(187, "div")(188, "h2");
            i0.ɵɵtext(189, "From Event to Entry in ");
            i0.ɵɵelementStart(190, "em");
            i0.ɵɵtext(191, "Minutes");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(192, "p");
            i0.ɵɵtext(193, "A simple and seamless booking experience.");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(194, "div", 47)(195, "article")(196, "span", 48);
            i0.ɵɵtext(197, "1");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(198, "b", 49);
            i0.ɵɵtext(199, "\u2315");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(200, "h3");
            i0.ɵɵtext(201, "Discover");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(202, "p");
            i0.ɵɵtext(203, "Find an event you love.");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(204, "article")(205, "span", 48);
            i0.ɵɵtext(206, "2");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(207, "b", 50);
            i0.ɵɵtext(208, "\u25C6");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(209, "h3");
            i0.ɵɵtext(210, "Choose Ticket / Seat");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(211, "p");
            i0.ɵɵtext(212, "Select your ticket and seat when applicable.");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(213, "article")(214, "span", 48);
            i0.ɵɵtext(215, "3");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(216, "b", 51);
            i0.ɵɵtext(217, "P");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(218, "i");
            i0.ɵɵtext(219, "Optional");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(220, "h3");
            i0.ɵɵtext(221, "Reserve Parking");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(222, "p");
            i0.ɵɵtext(223, "Add a parking slot if you need one.");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(224, "article")(225, "span", 48);
            i0.ɵɵtext(226, "4");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(227, "b", 52);
            i0.ɵɵtext(228, "\u25A3");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(229, "h3");
            i0.ɵɵtext(230, "Pay & Get QR");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(231, "p");
            i0.ɵɵtext(232, "Complete your booking and receive your QR ticket.");
            i0.ɵɵelementEnd()()()();
            i0.ɵɵelementStart(233, "section", 53)(234, "div", 54)(235, "span");
            i0.ɵɵtext(236, "PARK");
            i0.ɵɵelement(237, "br");
            i0.ɵɵtext(238, "SMART.");
            i0.ɵɵelement(239, "br");
            i0.ɵɵelementStart(240, "em");
            i0.ɵɵtext(241, "EVENT");
            i0.ɵɵelement(242, "br");
            i0.ɵɵtext(243, "HAPPIER.");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(244, "div", 55)(245, "span", 56);
            i0.ɵɵtext(246, "\uD83D\uDE98 Smart Event Parking");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(247, "h2");
            i0.ɵɵtext(248, "Your parking spot can be ready before you arrive.");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(249, "p");
            i0.ɵɵtext(250, "See available parking for your event, select a slot, and keep your parking details together with your booking.");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(251, "ul")(252, "li");
            i0.ɵɵtext(253, "Live slot availability");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(254, "li");
            i0.ɵɵtext(255, "Clear parking zones");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(256, "li");
            i0.ɵɵtext(257, "Optional during booking");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(258, "li");
            i0.ɵɵtext(259, "One booking, ticket + parking");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(260, "a", 57);
            i0.ɵɵtext(261, "See How Parking Works \u2192");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(262, "div", 58);
            i0.ɵɵrepeaterCreate(263, Landing_For_264_Template, 4, 6, "button", 59, i0.ɵɵrepeaterTrackByIdentity);
            i0.ɵɵelementStart(265, "div", 60)(266, "span");
            i0.ɵɵtext(267, "\u25CF Available");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(268, "span");
            i0.ɵɵtext(269, "\u25CF Selected");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(270, "span");
            i0.ɵɵtext(271, "\u25CF Occupied");
            i0.ɵɵelementEnd()()()();
            i0.ɵɵelementStart(272, "section", 61)(273, "div", 41)(274, "div")(275, "h2");
            i0.ɵɵtext(276, "Built for ");
            i0.ɵɵelementStart(277, "em");
            i0.ɵɵtext(278, "Everyone");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(279, "p");
            i0.ɵɵtext(280, "Different roles, one seamless platform.");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(281, "div", 62)(282, "article", 63)(283, "span", 64);
            i0.ɵɵtext(284, "\u265F");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(285, "div")(286, "h3");
            i0.ɵɵtext(287, "Customer");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(288, "p");
            i0.ɵɵtext(289, "Discover events, reserve tickets, seats and parking.");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(290, "button", 65);
            i0.ɵɵtext(291, "Create Customer Account \u2192");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(292, "article")(293, "span", 66);
            i0.ɵɵtext(294, "\u265F");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(295, "div")(296, "h3");
            i0.ɵɵtext(297, "Organizer");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(298, "p");
            i0.ɵɵtext(299, "Create events, configure tickets, seats and parking.");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(300, "button", 67);
            i0.ɵɵtext(301, "Organizer Login \u2192");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(302, "article")(303, "span", 68);
            i0.ɵɵtext(304, "\u2699");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(305, "div")(306, "h3");
            i0.ɵɵtext(307, "Admin");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(308, "p");
            i0.ɵɵtext(309, "Manage events, approvals, bookings and activity.");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(310, "button", 67);
            i0.ɵɵtext(311, "Admin Login \u2192");
            i0.ɵɵelementEnd()()()();
            i0.ɵɵelementStart(312, "section", 69)(313, "article")(314, "b");
            i0.ɵɵtext(315, "\u265F");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(316, "span")(317, "strong");
            i0.ɵɵtext(318, "10,000+");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(319, "small");
            i0.ɵɵtext(320, "Happy Customers");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(321, "article")(322, "b");
            i0.ɵɵtext(323, "\u25A3");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(324, "span")(325, "strong");
            i0.ɵɵtext(326, "500+");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(327, "small");
            i0.ɵɵtext(328, "Events Hosted");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(329, "article")(330, "b");
            i0.ɵɵtext(331, "\uD83D\uDE98");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(332, "span")(333, "strong");
            i0.ɵɵtext(334, "3,000+");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(335, "small");
            i0.ɵɵtext(336, "Parking Slots");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(337, "article")(338, "b");
            i0.ɵɵtext(339, "\u2605");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(340, "span")(341, "strong");
            i0.ɵɵtext(342, "4.8/5");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(343, "small");
            i0.ɵɵtext(344, "User Satisfaction");
            i0.ɵɵelementEnd()()()();
            i0.ɵɵelementStart(345, "section", 70)(346, "div")(347, "h2");
            i0.ɵɵtext(348, "Your Next Event Starts Here.");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(349, "p");
            i0.ɵɵtext(350, "Find an event, book your seat and arrive with confidence.");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(351, "a", 71);
            i0.ɵɵtext(352, "Explore Events \u2192");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(353, "button", 72);
            i0.ɵɵtext(354, "Create Free Account");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(355, "span");
            i0.ɵɵtext(356, "Live Events.");
            i0.ɵɵelement(357, "br");
            i0.ɵɵtext(358, "Better Together.");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(359, "footer", 73)(360, "div", 74)(361, "div")(362, "a", 75)(363, "span", 76);
            i0.ɵɵtext(364, "\u2726");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(365, "span")(366, "strong");
            i0.ɵɵtext(367, "Eventora");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(368, "small");
            i0.ɵɵtext(369, "Events \u2022 Tickets \u2022 Parking");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(370, "p");
            i0.ɵɵtext(371, "Your complete event and parking reservation platform. Simple. Secure. Reliable.");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(372, "div", 77);
            i0.ɵɵtext(373, "f\u3000\u25CE\u3000\uD835\uDD4F\u3000\u25B6\u3000in");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(374, "div")(375, "h3");
            i0.ɵɵtext(376, "Explore");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(377, "a", 7);
            i0.ɵɵtext(378, "Events");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(379, "a", 7);
            i0.ɵɵtext(380, "Categories");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(381, "a", 9);
            i0.ɵɵtext(382, "Parking");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(383, "a", 7);
            i0.ɵɵtext(384, "Venues");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(385, "div")(386, "h3");
            i0.ɵɵtext(387, "Account");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(388, "a", 78);
            i0.ɵɵtext(389, "Login");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(390, "a", 79);
            i0.ɵɵtext(391, "Register");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(392, "a", 7);
            i0.ɵɵtext(393, "My Bookings");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(394, "a", 9);
            i0.ɵɵtext(395, "My Parking");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(396, "div")(397, "h3");
            i0.ɵɵtext(398, "Support");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(399, "a", 11);
            i0.ɵɵtext(400, "Help Center");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(401, "a", 11);
            i0.ɵɵtext(402, "Contact Us");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(403, "a", 11);
            i0.ɵɵtext(404, "FAQ");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(405, "a", 11);
            i0.ɵɵtext(406, "Live Chat");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(407, "div")(408, "h3");
            i0.ɵɵtext(409, "Legal");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(410, "a", 11);
            i0.ɵɵtext(411, "Privacy Policy");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(412, "a", 11);
            i0.ɵɵtext(413, "Terms & Conditions");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(414, "a", 11);
            i0.ɵɵtext(415, "Cookie Policy");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(416, "a", 11);
            i0.ɵɵtext(417, "Refund Policy");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(418, "div", 80)(419, "span");
            i0.ɵɵtext(420, "\u00A9 2026 Eventora. All rights reserved.");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(421, "span");
            i0.ɵɵtext(422, "Made with ");
            i0.ɵɵelementStart(423, "b");
            i0.ɵɵtext(424, "\u2665");
            i0.ɵɵelementEnd();
            i0.ɵɵtext(425, " for better events");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(426, "a", 81);
            i0.ɵɵtext(427, "\u2191");
            i0.ɵɵelementEnd()();
        } if (rf & 2) {
            i0.ɵɵadvance(12);
            i0.ɵɵclassProp("open", ctx.menuOpen());
            i0.ɵɵadvance(97);
            i0.ɵɵproperty("value", ctx.query());
            i0.ɵɵadvance(18);
            i0.ɵɵproperty("value", ctx.selectedCategory());
            i0.ɵɵadvance(53);
            i0.ɵɵconditional(ctx.searchMessage() ? 180 : -1);
            i0.ɵɵadvance(2);
            i0.ɵɵrepeater(ctx.filteredEvents());
            i0.ɵɵadvance(81);
            i0.ɵɵrepeater(i0.ɵɵpureFunction0(6, _c0));
        } }, dependencies: [RouterLink], styles: ["[_nghost-%COMP%] { --%NS%ink:#10163e; --%NS%muted:#66708c; --%NS%purple:#6d28e8; --%NS%green:#13a768; display:block; overflow:hidden; }\n.shell[_ngcontent-%COMP%] { width:min(1120px,calc(100% - 40px)); margin-inline:auto; }\n.hero[_ngcontent-%COMP%] { min-height:500px; color:#fff; position:relative; background-image:linear-gradient(90deg,rgba(5,18,52,.98) 0%,rgba(6,16,49,.92) 33%,rgba(11,21,66,.3) 65%,rgba(7,18,56,.35)),url('/assets/concert-hero.webp'); background-size:cover; background-position:center; isolation:isolate; }\n.hero[_ngcontent-%COMP%]::after { content:''; position:absolute; inset:auto 0 0; height:80px; background:linear-gradient(177deg,transparent 48%,#fbfcff 49%); z-index:-1; }\n.nav[_ngcontent-%COMP%] { height:74px; display:flex; align-items:center; justify-content:space-between; gap:26px; }\n.brand[_ngcontent-%COMP%] { display:inline-flex; align-items:center; gap:11px; text-decoration:none; min-width:180px; }\n.brand-mark[_ngcontent-%COMP%] { font-size:42px; line-height:1; transform:rotate(14deg); display:inline-block; }\n.brand[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%] { font-size:21px; display:block; letter-spacing:-.4px; }.brand[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { display:block; font-size:10px; opacity:.8; margin-top:-1px; }\n.nav-links[_ngcontent-%COMP%] { display:flex; gap:28px; align-items:center; margin-left:auto; }.nav-links[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] { text-decoration:none; font-size:13px; position:relative; padding:26px 0; }.nav-links[_ngcontent-%COMP%]   .active[_ngcontent-%COMP%] { color:#c88dff; }.nav-links[_ngcontent-%COMP%]   .active[_ngcontent-%COMP%]::after { content:''; position:absolute; height:2px; inset:auto 0 17px; background:#b868ff; }\n.nav-actions[_ngcontent-%COMP%] { display:flex; gap:12px; align-items:center; }.btn[_ngcontent-%COMP%] { border:0; border-radius:9px; padding:11px 21px; font-weight:700; font-size:13px; cursor:pointer; text-decoration:none; display:inline-flex; align-items:center; justify-content:center; gap:10px; transition:transform .2s,box-shadow .2s,background .2s; }.btn[_ngcontent-%COMP%]:hover { transform:translateY(-2px); }.btn-primary[_ngcontent-%COMP%] { color:#fff; background:linear-gradient(135deg,#8549ff,#5f20dd); box-shadow:0 8px 24px rgba(91,35,221,.28); }.btn-white[_ngcontent-%COMP%] { color:#292164; background:#fff; }.btn-outline[_ngcontent-%COMP%] { background:rgba(19,25,66,.18); color:#fff; border:1px solid rgba(255,255,255,.7); }.btn-soft[_ngcontent-%COMP%] { color:#342680; background:#fff; border:1px solid #d8ddef; }.icon-button[_ngcontent-%COMP%] { width:34px; height:34px; border:0; color:#fff; background:transparent; font-size:28px; cursor:pointer; }.menu-toggle[_ngcontent-%COMP%] { display:none; color:#fff; border:0; background:transparent; font-size:25px; }\n.hero-content[_ngcontent-%COMP%] { min-height:390px; display:grid; grid-template-columns:1.22fr 1fr 150px; align-items:center; gap:34px; padding-bottom:78px; }\n.hero-copy[_ngcontent-%COMP%] { max-width:480px; }.eyebrow[_ngcontent-%COMP%] { display:inline-block; background:#fff; color:#4335a2; border-radius:999px; padding:7px 16px; font-size:12px; font-weight:700; margin-bottom:14px; }.hero[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%] { font-size:clamp(37px,4vw,53px); line-height:1.03; letter-spacing:-2px; margin:0 0 13px; }.hero[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%]   em[_ngcontent-%COMP%], h2[_ngcontent-%COMP%]   em[_ngcontent-%COMP%] { font-style:normal; color:#9c59ff; }.hero-copy[_ngcontent-%COMP%] > p[_ngcontent-%COMP%] { font-size:15px; line-height:1.55; max-width:500px; margin:0 0 16px; color:#ecedfa; }.hero-buttons[_ngcontent-%COMP%] { display:flex; gap:15px; margin-bottom:16px; }.btn-large[_ngcontent-%COMP%] { min-width:150px; padding:13px 23px; }.trust-row[_ngcontent-%COMP%] { display:flex; gap:22px; font-size:10px; }.trust-row[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] { color:#e9ecf9; }\n.booking-preview[_ngcontent-%COMP%] { transform:translateY(8px); }.preview-card[_ngcontent-%COMP%] { color:var(--%NS%ink); background:rgba(255,255,255,.95); border-radius:11px; padding:13px; display:flex; gap:11px; align-items:flex-start; box-shadow:0 16px 35px rgba(6,12,54,.24); }.preview-card[_ngcontent-%COMP%]   div[_ngcontent-%COMP%] { flex:1; min-width:0; }.preview-card[_ngcontent-%COMP%]   small[_ngcontent-%COMP%], .preview-card[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] { display:block; font-size:9px; color:#59637f; }.preview-card[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%] { display:block; font-size:13px; margin:2px 0 5px; }.preview-card[_ngcontent-%COMP%] > b[_ngcontent-%COMP%] { border-radius:50%; background:#e9e0ff; color:#6c28e7; padding:6px 9px; align-self:center; }.preview-icon[_ngcontent-%COMP%] { flex:0 0 30px; height:30px; border-radius:7px; display:grid!important; place-items:center; color:#fff!important; font-size:16px!important; }.pink[_ngcontent-%COMP%] { background:#ee4d8d!important; color:#fff!important; }.violet[_ngcontent-%COMP%] { background:#7a42ef!important; }.green[_ngcontent-%COMP%] { background:#16a86c!important; color:#fff!important; }.blue[_ngcontent-%COMP%] { background:#2081e8!important; color:#fff!important; }.preview-pair[_ngcontent-%COMP%] { display:grid; grid-template-columns:1fr 1fr; gap:9px; margin-top:9px; }.preview-card[_ngcontent-%COMP%]   i[_ngcontent-%COMP%] { font-style:normal; display:inline-block; font-size:9px; color:#138553; background:#c9f4dc; padding:4px 8px; border-radius:999px; }\n.ticket-phone[_ngcontent-%COMP%] { width:132px; height:250px; transform:rotate(7deg); border:7px solid #121941; border-radius:23px; background:linear-gradient(#7751dc 0 38px,#fff 38px); padding:13px 12px; color:#141844; text-align:center; box-shadow:0 22px 55px #050a2e; }.ticket-phone[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { display:block; color:#fff; margin-bottom:28px; font-size:9px; }.ticket-phone[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%] { display:block; font-size:9px; margin-top:10px; }.ticket-phone[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] { font-size:8px; color:#5e6682; }.qr-pattern[_ngcontent-%COMP%] { width:72px; height:72px; margin:auto; border:5px solid #fff; background:repeating-conic-gradient(#0e123e 0 25%,#fff 0 50%) 0/14px 14px; box-shadow:inset 0 0 0 2px #fff; }\n.search-wrap[_ngcontent-%COMP%] { margin-top:-47px; position:relative; z-index:4; background:#fff; border:1px solid #e5e8f3; border-radius:16px; padding:18px 20px 13px; box-shadow:0 18px 40px rgba(53,63,111,.16); }.search-grid[_ngcontent-%COMP%] { display:grid; grid-template-columns:1.6fr 1.12fr 1.12fr 1.1fr .82fr; gap:10px; }.search-field[_ngcontent-%COMP%], .select-field[_ngcontent-%COMP%] { min-width:0; height:50px; border:1px solid #dfe4f2; border-radius:10px; display:grid; align-items:center; background:#fff; }.search-field[_ngcontent-%COMP%] { grid-template-columns:36px 1fr; padding:0 10px; }.search-field[_ngcontent-%COMP%] > span[_ngcontent-%COMP%], .select-field[_ngcontent-%COMP%] > span[_ngcontent-%COMP%] { color:#682fe9; font-size:24px; }.search-field[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] { border:0; outline:0; min-width:0; font-size:11px; }.select-field[_ngcontent-%COMP%] { grid-template-columns:32px 1fr; grid-template-rows:20px 20px; padding:5px 9px; }.select-field[_ngcontent-%COMP%] > span[_ngcontent-%COMP%] { grid-row:1/3; }.select-field[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { color:#273052; font-size:9px; align-self:end; }.select-field[_ngcontent-%COMP%]   select[_ngcontent-%COMP%] { border:0; outline:0; min-width:0; color:#626b87; font-size:9px; background:transparent; }.find-btn[_ngcontent-%COMP%] { height:50px; }.category-row[_ngcontent-%COMP%] { display:flex; justify-content:center; align-items:center; gap:8px; margin-top:12px; font-size:9px; }.category-row[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] { border:0; border-radius:999px; min-width:90px; padding:7px 12px; color:#2b3470; background:#edf2ff; cursor:pointer; }.category-row[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]:nth-of-type(1), .category-row[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]:nth-of-type(5){background:#f0ddff}.category-row[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]:nth-of-type(2){background:#d9f4e7}.category-row[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]:nth-of-type(4){background:#ffe9dd}\n.section[_ngcontent-%COMP%] { padding-top:22px; }.section-head[_ngcontent-%COMP%] { display:flex; justify-content:space-between; align-items:end; margin-bottom:12px; }.section-head[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] { margin:0; font-size:26px; line-height:1.1; letter-spacing:-.7px; }.section-head[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { margin:4px 0 0; color:var(--%NS%muted); font-size:12px; }.section-head[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] { color:#6125db; text-decoration:none; font-size:12px; font-weight:700; }.search-message[_ngcontent-%COMP%] { margin:-3px 0 10px; color:#6030d4; font-size:12px; font-weight:700; }.event-grid[_ngcontent-%COMP%] { display:grid; grid-template-columns:repeat(4,1fr); gap:16px; }.event-card[_ngcontent-%COMP%] { background:#fff; border-radius:11px; overflow:hidden; box-shadow:0 9px 25px rgba(42,55,105,.12); }.event-image[_ngcontent-%COMP%] { height:123px; position:relative; background-image:url('/assets/event-grid.png'); background-size:400% 100%; }.date-badge[_ngcontent-%COMP%] { position:absolute; top:11px; left:11px; width:40px; height:45px; border-radius:7px; background:#fff; display:grid; place-items:center; align-content:center; font-size:8px; color:#3f3298; font-weight:700; line-height:1.1; }.date-badge[_ngcontent-%COMP%]   b[_ngcontent-%COMP%] { font-size:18px; }.heart[_ngcontent-%COMP%] { position:absolute; top:8px; right:9px; width:30px; height:30px; border:0; color:#fff; background:rgba(5,13,45,.5); font-size:24px; line-height:1; border-radius:50%; cursor:pointer; }.heart.saved[_ngcontent-%COMP%] { color:#ff4c83; background:#fff; }.category-badge[_ngcontent-%COMP%] { position:absolute; bottom:8px; left:10px; padding:4px 10px; border-radius:999px; color:#fff; background:#3a69e9; font-size:9px; }.event-body[_ngcontent-%COMP%] { padding:10px 13px 11px; }.event-body[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { margin:0 0 7px; font-size:14px; }.event-body[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { margin:4px 0; color:#66708b; font-size:10px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }.event-body[_ngcontent-%COMP%] > div[_ngcontent-%COMP%] { display:flex; align-items:end; justify-content:space-between; margin-top:5px; font-size:10px; }.event-body[_ngcontent-%COMP%] > div[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%] { font-size:14px; }.event-body[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { padding:5px 7px; border-radius:6px; color:#312478; background:#e5e3ff; font-size:8px; font-weight:700; }.empty-state[_ngcontent-%COMP%] { grid-column:1/-1; padding:35px; text-align:center; color:var(--%NS%muted); background:#fff; border-radius:12px; }\n.how[_ngcontent-%COMP%] { padding-top:21px; }.steps[_ngcontent-%COMP%] { display:grid; grid-template-columns:repeat(4,1fr); gap:44px; }.steps[_ngcontent-%COMP%]   article[_ngcontent-%COMP%] { position:relative; padding-left:52px; min-height:78px; }.steps[_ngcontent-%COMP%]   article[_ngcontent-%COMP%]:not(:last-child)::after { content:''; position:absolute; top:21px; left:calc(100% + 3px); width:40px; border-top:1px dashed #b9c6ed; }.step-number[_ngcontent-%COMP%] { position:absolute; left:0; top:12px; width:23px; height:23px; display:grid; place-items:center; color:#fff; background:#6427df; border-radius:50%; font-size:10px; }.step-icon[_ngcontent-%COMP%] { width:43px; height:43px; display:grid; place-items:center; border-radius:50%; background:#eee9ff; color:#6329dc; font-size:24px; margin-bottom:5px; }.steps[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { font-size:13px; margin:0 0 3px; }.steps[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { color:var(--%NS%muted); font-size:10px; margin:0; line-height:1.3; }.steps[_ngcontent-%COMP%]   i[_ngcontent-%COMP%] { position:absolute; top:13px; right:0; font-style:normal; color:#19885b; background:#d8f5e6; font-size:8px; padding:4px 10px; border-radius:999px; }\n.parking-feature[_ngcontent-%COMP%] { min-height:285px; margin-top:24px; display:grid; grid-template-columns:1.35fr 1.1fr .92fr; background:#fff; border:1px solid #e7e9f3; border-radius:13px; overflow:hidden; box-shadow:0 10px 30px rgba(39,49,98,.1); }.parking-photo[_ngcontent-%COMP%] { min-height:285px; padding:55px 35px; display:flex; align-items:center; color:#fff; background:linear-gradient(90deg,rgba(21,26,80,.76),rgba(21,26,80,.08)),url('/assets/smart-parking.png') center/cover; }.parking-photo[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] { font-size:28px; font-weight:800; line-height:.95; }.parking-photo[_ngcontent-%COMP%]   em[_ngcontent-%COMP%] { font-style:normal; color:#b888ff; }.parking-copy[_ngcontent-%COMP%] { padding:22px 18px; align-self:center; }.smart-pill[_ngcontent-%COMP%] { color:#167c54; background:#d8f5e7; border-radius:999px; padding:5px 10px; font-size:9px; }.parking-copy[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] { margin:10px 0 7px; font-size:20px; line-height:1.05; }.parking-copy[_ngcontent-%COMP%]   p[_ngcontent-%COMP%], .parking-copy[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] { color:var(--%NS%muted); font-size:10px; line-height:1.4; }.parking-copy[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%] { padding:0; list-style:none; margin:8px 0 12px; }.parking-copy[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]::before { content:'\u2713'; color:#fff; background:#10a568; border-radius:50%; padding:0 3px; margin-right:8px; }.parking-copy[_ngcontent-%COMP%]   .btn[_ngcontent-%COMP%] { padding:10px 17px; }.parking-map[_ngcontent-%COMP%] { margin:12px; padding:10px; border:1px solid #e4e8f1; background:#f8faff; border-radius:11px; display:grid; grid-template-columns:repeat(3,1fr); gap:8px; }.parking-map[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] { min-height:56px; border:0; border-radius:7px; background:#e6ebf4; color:#27304f; font-size:9px; }.parking-map[_ngcontent-%COMP%]   button.selected[_ngcontent-%COMP%] { color:#fff; background:#13bf77; box-shadow:0 7px 18px rgba(19,191,119,.35); }.parking-map[_ngcontent-%COMP%]   button.busy[_ngcontent-%COMP%] { background:#f7dbe3; }.parking-map[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { display:block; font-size:12px; }.parking-legend[_ngcontent-%COMP%] { grid-column:1/-1; display:flex; justify-content:space-around; font-size:7px; color:#65708a; }.parking-legend[_ngcontent-%COMP%]   span[_ngcontent-%COMP%]:nth-child(2){color:#10a76a}.parking-legend[_ngcontent-%COMP%]   span[_ngcontent-%COMP%]:nth-child(3){color:#e7476d}\n.roles[_ngcontent-%COMP%] { padding-top:22px; }.role-grid[_ngcontent-%COMP%] { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-left:310px; margin-top:-44px; }.role-grid[_ngcontent-%COMP%]   article[_ngcontent-%COMP%] { min-height:116px; padding:12px; border-radius:11px; background:#fff; box-shadow:0 8px 24px rgba(47,61,109,.1); display:grid; grid-template-columns:45px 1fr; gap:10px; }.role-grid[_ngcontent-%COMP%]   article.featured[_ngcontent-%COMP%] { border:1.5px solid #8c4cff; }.role-icon[_ngcontent-%COMP%] { width:42px; height:42px; display:grid; place-items:center; border-radius:10px; color:#6930dc; background:#e9ddff; font-size:23px; }.role-grid[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { margin:2px 0 1px; font-size:13px; }.role-grid[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { margin:0; color:var(--%NS%muted); font-size:9px; line-height:1.2; }.role-grid[_ngcontent-%COMP%]   .btn[_ngcontent-%COMP%] { grid-column:1/-1; padding:7px; font-size:9px; }.stats[_ngcontent-%COMP%] { margin-top:16px; padding:11px 24px; border-radius:10px; background:linear-gradient(90deg,#f1ecff,#f8fbff,#fff2e9); display:grid; grid-template-columns:repeat(4,1fr); }.stats[_ngcontent-%COMP%]   article[_ngcontent-%COMP%] { display:flex; align-items:center; justify-content:center; gap:12px; border-right:1px solid #dfe5f2; }.stats[_ngcontent-%COMP%]   article[_ngcontent-%COMP%]:last-child { border:0; }.stats[_ngcontent-%COMP%]   b[_ngcontent-%COMP%] { font-size:22px; color:#6530db; }.stats[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%], .stats[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { display:block; }.stats[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%] { font-size:15px; }.stats[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { font-size:8px; color:var(--%NS%muted); }\n.final-cta[_ngcontent-%COMP%] { min-height:138px; margin-top:17px; margin-bottom:14px; padding:28px 38px; border-radius:12px; color:#fff; background:linear-gradient(90deg,rgba(52,25,143,.93),rgba(73,35,172,.63),rgba(56,27,135,.5)),url('/assets/concert-hero.png') center 70%/cover; display:flex; justify-content:space-between; align-items:center; }.final-cta[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] { margin:0 0 4px; font-size:27px; }.final-cta[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { margin:0 0 12px; font-size:12px; }.final-cta[_ngcontent-%COMP%]   .btn[_ngcontent-%COMP%] { padding:10px 18px; margin-right:10px; }.final-cta[_ngcontent-%COMP%] > span[_ngcontent-%COMP%] { font-size:21px; font-style:italic; transform:rotate(-6deg); }\nfooter[_ngcontent-%COMP%] { color:#fff; background:radial-gradient(circle at 70% 0,#10295f,#07172f 55%,#071329); padding:28px 0 12px; position:relative; }.footer-grid[_ngcontent-%COMP%] { display:grid; grid-template-columns:1.7fr repeat(4,1fr); gap:48px; }.footer-grid[_ngcontent-%COMP%]   .brand[_ngcontent-%COMP%] { margin-bottom:12px; }.footer-grid[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { color:#b8c2d8; font-size:9px; line-height:1.5; max-width:230px; }.socials[_ngcontent-%COMP%] { margin-top:12px; font-size:15px; }.footer-grid[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { font-size:11px; margin:5px 0 11px; }.footer-grid[_ngcontent-%COMP%] > div[_ngcontent-%COMP%] > a[_ngcontent-%COMP%]:not(.brand) { color:#b8c2d8; text-decoration:none; font-size:9px; display:block; margin:7px 0; }.footer-bottom[_ngcontent-%COMP%] { margin-top:22px; display:flex; justify-content:space-between; color:#aab6ce; font-size:8px; }.footer-bottom[_ngcontent-%COMP%]   b[_ngcontent-%COMP%] { color:#f14873; }.back-top[_ngcontent-%COMP%] { position:absolute; right:25px; bottom:26px; width:34px; height:34px; border-radius:50%; color:#fff; background:#6d2cea; display:grid; place-items:center; text-decoration:none; }\n@media (max-width:960px) { .nav-links[_ngcontent-%COMP%]{gap:15px}.nav-links[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{font-size:11px}.nav-actions[_ngcontent-%COMP%]   .btn[_ngcontent-%COMP%]{display:none}.hero-content[_ngcontent-%COMP%]{grid-template-columns:1fr .9fr}.ticket-phone[_ngcontent-%COMP%]{display:none}.search-grid[_ngcontent-%COMP%]{grid-template-columns:1.5fr 1fr 1fr}.search-grid[_ngcontent-%COMP%] > [_ngcontent-%COMP%]:nth-child(4){grid-column:1/2}.find-btn[_ngcontent-%COMP%]{grid-column:2/4}.category-row[_ngcontent-%COMP%]{flex-wrap:wrap}.event-grid[_ngcontent-%COMP%]{grid-template-columns:repeat(2,1fr)}.steps[_ngcontent-%COMP%]{grid-template-columns:repeat(2,1fr);row-gap:25px}.steps[_ngcontent-%COMP%]   article[_ngcontent-%COMP%]::after{display:none}.parking-feature[_ngcontent-%COMP%]{grid-template-columns:1fr 1fr}.parking-map[_ngcontent-%COMP%]{grid-column:1/-1}.role-grid[_ngcontent-%COMP%]{margin-left:0;margin-top:0}.footer-grid[_ngcontent-%COMP%]{grid-template-columns:1.5fr repeat(2,1fr)}.footer-grid[_ngcontent-%COMP%] > div[_ngcontent-%COMP%]:nth-child(4), .footer-grid[_ngcontent-%COMP%] > div[_ngcontent-%COMP%]:nth-child(5){display:none} }\n@media (max-width:700px) { .shell[_ngcontent-%COMP%]{width:min(100% - 24px,1120px)}.nav[_ngcontent-%COMP%]{height:64px}.menu-toggle[_ngcontent-%COMP%]{display:block;order:3}.nav-links[_ngcontent-%COMP%]{display:none;position:absolute;top:62px;left:12px;right:12px;z-index:9;flex-direction:column;align-items:stretch;gap:0;padding:10px 18px;border-radius:12px;background:#0d1840}.nav-links.open[_ngcontent-%COMP%]{display:flex}.nav-links[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{padding:11px}.nav-links[_ngcontent-%COMP%]   .active[_ngcontent-%COMP%]::after{display:none}.nav-actions[_ngcontent-%COMP%]{margin-left:auto}.hero[_ngcontent-%COMP%]{min-height:640px}.hero-content[_ngcontent-%COMP%]{display:block;padding-top:35px}.hero[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%]{font-size:40px}.booking-preview[_ngcontent-%COMP%]{margin-top:28px;max-width:430px}.trust-row[_ngcontent-%COMP%]{gap:10px;flex-wrap:wrap}.search-wrap[_ngcontent-%COMP%]{margin-top:-44px}.search-grid[_ngcontent-%COMP%]{grid-template-columns:1fr 1fr}.search-field[_ngcontent-%COMP%]{grid-column:1/-1}.find-btn[_ngcontent-%COMP%]{grid-column:1/-1}.category-row[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%]{width:100%;text-align:center}.category-row[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]{min-width:auto}.section-head[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%]{font-size:22px}.event-grid[_ngcontent-%COMP%]{grid-template-columns:1fr}.event-image[_ngcontent-%COMP%]{height:180px}.steps[_ngcontent-%COMP%]{grid-template-columns:1fr}.parking-feature[_ngcontent-%COMP%]{grid-template-columns:1fr}.parking-photo[_ngcontent-%COMP%]{min-height:230px}.role-grid[_ngcontent-%COMP%]{grid-template-columns:1fr}.stats[_ngcontent-%COMP%]{grid-template-columns:1fr 1fr;gap:12px}.stats[_ngcontent-%COMP%]   article[_ngcontent-%COMP%]:nth-child(2){border-right:0}.final-cta[_ngcontent-%COMP%]{padding:24px}.final-cta[_ngcontent-%COMP%] > span[_ngcontent-%COMP%]{display:none}.footer-grid[_ngcontent-%COMP%]{grid-template-columns:1.4fr 1fr;gap:25px}.footer-grid[_ngcontent-%COMP%] > div[_ngcontent-%COMP%]:nth-child(3){display:none} }\n@media (max-width:440px) { .brand[_ngcontent-%COMP%]{min-width:0}.brand-mark[_ngcontent-%COMP%]{font-size:34px}.brand[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%]{font-size:18px}.icon-button[_ngcontent-%COMP%]{display:none}.hero[_ngcontent-%COMP%]{min-height:665px}.hero[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%]{font-size:35px}.preview-pair[_ngcontent-%COMP%]{grid-template-columns:1fr}.booking-preview[_ngcontent-%COMP%]   .upcoming[_ngcontent-%COMP%]{display:none}.search-grid[_ngcontent-%COMP%]{grid-template-columns:1fr}.search-grid[_ngcontent-%COMP%] > *[_ngcontent-%COMP%]{grid-column:1!important}.select-field[_ngcontent-%COMP%]:nth-of-type(4){display:none}.event-image[_ngcontent-%COMP%]{height:155px}.parking-copy[_ngcontent-%COMP%]{padding:22px}.footer-grid[_ngcontent-%COMP%]{grid-template-columns:1fr 1fr}.footer-grid[_ngcontent-%COMP%] > div[_ngcontent-%COMP%]:first-child{grid-column:1/-1}.footer-bottom[_ngcontent-%COMP%]{gap:20px}.final-cta[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%]{font-size:23px} }\n\n\n.nav-links[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] { font-size:14px; }\n.eyebrow[_ngcontent-%COMP%] { font-size:14px; }\n.hero-copy[_ngcontent-%COMP%] > p[_ngcontent-%COMP%] { font-size:17px; }\n.trust-row[_ngcontent-%COMP%] { font-size:12px; }\n.preview-card[_ngcontent-%COMP%] { padding:15px; }\n.preview-card[_ngcontent-%COMP%]   small[_ngcontent-%COMP%], .preview-card[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] { font-size:12px; line-height:1.35; }\n.preview-card[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%] { font-size:16px; }\n.preview-card[_ngcontent-%COMP%]   i[_ngcontent-%COMP%] { font-size:11px; }\n.search-field[_ngcontent-%COMP%], .select-field[_ngcontent-%COMP%], .find-btn[_ngcontent-%COMP%] { height:58px; }\n.search-field[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] { font-size:14px; }\n.select-field[_ngcontent-%COMP%] { grid-template-rows:23px 23px; }\n.select-field[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { font-size:12px; }\n.select-field[_ngcontent-%COMP%]   select[_ngcontent-%COMP%] { font-size:12px; }\n.category-row[_ngcontent-%COMP%] { font-size:12px; }\n.category-row[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] { font-size:12px; padding:8px 14px; }\n.section-head[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { font-size:15px; }\n.section-head[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] { font-size:14px; }\n.event-image[_ngcontent-%COMP%] { height:180px; background-size:400% auto; background-repeat:no-repeat; background-color:#11183f; }\n.event-body[_ngcontent-%COMP%] { padding:14px 15px 15px; }\n.event-body[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { font-size:18px; margin-bottom:9px; }\n.event-body[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { font-size:14px; margin:7px 0; }\n.event-body[_ngcontent-%COMP%] > div[_ngcontent-%COMP%] { font-size:13px; margin-top:8px; }\n.event-body[_ngcontent-%COMP%] > div[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%] { font-size:18px; }\n.event-body[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { font-size:11px; }\n.date-badge[_ngcontent-%COMP%] { width:46px; height:52px; font-size:10px; }\n.date-badge[_ngcontent-%COMP%]   b[_ngcontent-%COMP%] { font-size:20px; }\n.category-badge[_ngcontent-%COMP%] { font-size:11px; }\n.steps[_ngcontent-%COMP%] { margin-top:18px; }\n.steps[_ngcontent-%COMP%]   article[_ngcontent-%COMP%] { min-height:110px; }\n.steps[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { font-size:16px; }\n.steps[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { font-size:14px; line-height:1.45; }\n.steps[_ngcontent-%COMP%]   i[_ngcontent-%COMP%] { font-size:11px; }\n.parking-feature[_ngcontent-%COMP%] { min-height:335px; }\n.parking-photo[_ngcontent-%COMP%] { min-height:335px; }\n.smart-pill[_ngcontent-%COMP%] { font-size:12px; }\n.parking-copy[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] { font-size:24px; line-height:1.12; }\n.parking-copy[_ngcontent-%COMP%]   p[_ngcontent-%COMP%], .parking-copy[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] { font-size:14px; line-height:1.5; }\n.parking-map[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] { font-size:12px; }\n.parking-legend[_ngcontent-%COMP%] { font-size:10px; }\n.role-grid[_ngcontent-%COMP%]   article[_ngcontent-%COMP%] { min-height:158px; padding:16px; }\n.role-grid[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { font-size:17px; }\n.role-grid[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { font-size:14px; line-height:1.4; }\n.role-grid[_ngcontent-%COMP%]   .btn[_ngcontent-%COMP%] { font-size:12px; }\n.stats[_ngcontent-%COMP%] { padding-block:16px; }\n.stats[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%] { font-size:18px; }\n.stats[_ngcontent-%COMP%]   small[_ngcontent-%COMP%] { font-size:12px; }\n.final-cta[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { font-size:15px; }\n.footer-grid[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] { font-size:13px; }\n.footer-grid[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { font-size:15px; }\n.footer-grid[_ngcontent-%COMP%] > div[_ngcontent-%COMP%] > a[_ngcontent-%COMP%]:not(.brand) { font-size:13px; margin:10px 0; }\n.footer-bottom[_ngcontent-%COMP%] { font-size:12px; }\n\n@media (max-width:960px) {\n  .nav-links[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] { font-size:12px; }\n  .role-grid[_ngcontent-%COMP%] { margin-top:0; }\n}\n@media (max-width:700px) {\n  .hero-copy[_ngcontent-%COMP%] > p[_ngcontent-%COMP%] { font-size:16px; }\n  .event-image[_ngcontent-%COMP%] { height:240px; }\n  .steps[_ngcontent-%COMP%]   article[_ngcontent-%COMP%] { min-height:96px; }\n  .footer-grid[_ngcontent-%COMP%] > div[_ngcontent-%COMP%] > a[_ngcontent-%COMP%]:not(.brand) { font-size:14px; }\n}\n\n.event-image[_ngcontent-%COMP%] { background-image:url('/assets/event-grid.webp'); }\n.parking-photo[_ngcontent-%COMP%] { background-image:linear-gradient(90deg,rgba(21,26,80,.76),rgba(21,26,80,.08)),url('/assets/smart-parking.webp'); }\n.final-cta[_ngcontent-%COMP%] { background-image:linear-gradient(90deg,rgba(52,25,143,.93),rgba(73,35,172,.63),rgba(56,27,135,.5)),url('/assets/concert-hero.webp'); }"] });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(Landing, [{
        type: Component,
        args: [{ selector: 'app-landing', standalone: true, imports: [RouterLink], template: "<header class=\"hero\" id=\"home\">\n  <nav class=\"nav shell\" aria-label=\"Main navigation\">\n    <a class=\"brand\" href=\"#home\" aria-label=\"Eventora home\">\n      <span class=\"brand-mark\" aria-hidden=\"true\">\u2726</span>\n      <span><strong>Eventora</strong><small>Events \u2022 Tickets \u2022 Parking</small></span>\n    </a>\n    <button class=\"menu-toggle\" type=\"button\" aria-label=\"Toggle menu\" (click)=\"menuOpen.set(!menuOpen())\">\u2630</button>\n    <div class=\"nav-links\" [class.open]=\"menuOpen()\">\n      <a class=\"active\" href=\"#home\">Home</a><a href=\"#events\">Events</a><a href=\"#how\">How It Works</a><a href=\"#parking\">Parking</a><a href=\"#roles\">About</a><a href=\"#footer\">Contact</a>\n    </div>\n    <div class=\"nav-actions\">\n      <button class=\"icon-button\" type=\"button\" aria-label=\"Search\">\u2315</button><a class=\"btn btn-white\" routerLink=\"/login\">Log In</a><button class=\"btn btn-primary\" type=\"button\">Create Account</button>\n    </div>\n  </nav>\n\n  <div class=\"hero-content shell\">\n    <div class=\"hero-copy\">\n      <span class=\"eyebrow\">Events \u2022 Tickets \u2022 Parking \u2014 All in One Place</span>\n      <h1>Book the Event.<br>Reserve Your Seat.<br><em>Park Without Stress.</em></h1>\n      <p>Discover events, choose your perfect seat, reserve parking, and manage everything from one seamless experience.</p>\n      <div class=\"hero-buttons\"><a class=\"btn btn-primary btn-large\" href=\"#events\">Explore Events <span>\u2192</span></a><a class=\"btn btn-outline btn-large\" href=\"#how\">Get Started</a></div>\n      <div class=\"trust-row\"><span>\u25CF Secure Booking</span><span>\u25CF Easy & Fast</span><span>\u25CF Parking is Optional</span></div>\n    </div>\n\n    <div class=\"booking-preview\" aria-label=\"Booking preview\">\n      <article class=\"preview-card upcoming\"><span class=\"preview-icon pink\">\u266B</span><div><small>Upcoming Event</small><strong>Summer Music Fest</strong><span>\u25F7 May 24, 2025 \u2022 6:00 PM</span><span>\u2316 Chennai Stadium</span></div><b>\u2192</b></article>\n      <div class=\"preview-pair\">\n        <article class=\"preview-card\"><span class=\"preview-icon violet\">\u2726</span><div><small>Your Tickets</small><strong>A1, A2</strong><i>Confirmed</i></div></article>\n        <article class=\"preview-card\"><span class=\"preview-icon green\">P</span><div><small>Parking Slot</small><strong>Zone B \u2022 B27</strong><i>Reserved</i></div></article>\n      </div>\n    </div>\n\n    <div class=\"ticket-phone\" aria-label=\"Digital ticket preview\"><small>\u2726 Eventora</small><div class=\"qr-pattern\" aria-hidden=\"true\"></div><strong>Your Event Ticket</strong><span>Scan at Entry</span></div>\n  </div>\n</header>\n\n<main>\n  <section class=\"search-wrap shell\" aria-label=\"Find events\">\n    <div class=\"search-grid\">\n      <label class=\"search-field wide\"><span>\u2315</span><input type=\"search\" placeholder=\"Search events, artists, or venues...\" [value]=\"query()\" (input)=\"updateQuery($event)\"></label>\n      <label class=\"select-field\"><span>\u2316</span><small>Location / Venue</small><select><option>All Locations</option><option>Chennai</option><option>Bengaluru</option></select></label>\n      <label class=\"select-field\"><span>\u25A6</span><small>Category</small><select [value]=\"selectedCategory()\" (change)=\"updateCategory($event)\"><option>All Categories</option><option>Concert</option><option>Sports</option><option>Conference</option><option>Festival</option></select></label>\n      <label class=\"select-field\"><span>\u25A3</span><small>Date</small><select><option>Any Date</option><option>This Week</option><option>This Month</option></select></label>\n      <button class=\"btn btn-primary find-btn\" type=\"button\" (click)=\"findEvents()\">Find Events <b>\u2192</b></button>\n    </div>\n    <div class=\"category-row\"><strong>Popular Categories:</strong><button>\u266B Concert</button><button>\uD83C\uDFC6 Sports</button><button>\u265F Conference</button><button>\u25A3 Workshop</button><button>\u25B2 Festival</button><button>\u25A6 Other</button></div>\n  </section>\n\n  <section class=\"section shell\" id=\"events\">\n    <div class=\"section-head\"><div><h2>Events <em>You\u2019ll Love</em></h2><p>Discover popular and upcoming experiences.</p></div><a href=\"#events\">View All Events \u2192</a></div>\n    @if (searchMessage()) { <p class=\"search-message\" role=\"status\">{{ searchMessage() }}</p> }\n    <div class=\"event-grid\">\n      @for (event of filteredEvents(); track event.title) {\n        <article class=\"event-card\">\n          <div class=\"event-image\" [style.background-position]=\"event.imagePosition\"><span class=\"date-badge\"><b>{{ event.day }}</b>{{ event.month }}</span><button class=\"heart\" type=\"button\" [class.saved]=\"favoriteTitles().has(event.title)\" (click)=\"toggleFavorite(event.title)\" [attr.aria-label]=\"'Save ' + event.title\">{{ favoriteTitles().has(event.title) ? '\u2665' : '\u2661' }}</button><span class=\"category-badge\">{{ event.category }}</span></div>\n          <div class=\"event-body\"><h3>{{ event.title }}</h3><p>\u2316 {{ event.venue }}</p><p>\u25F7 {{ event.time }}</p><div><span>From <strong>{{ event.price }}</strong></span><small>{{ event.ticketType }}</small></div></div>\n        </article>\n      } @empty { <div class=\"empty-state\">Try another search or category.</div> }\n    </div>\n  </section>\n\n  <section class=\"section shell how\" id=\"how\">\n    <div class=\"section-head\"><div><h2>From Event to Entry in <em>Minutes</em></h2><p>A simple and seamless booking experience.</p></div></div>\n    <div class=\"steps\">\n      <article><span class=\"step-number\">1</span><b class=\"step-icon\">\u2315</b><h3>Discover</h3><p>Find an event you love.</p></article>\n      <article><span class=\"step-number\">2</span><b class=\"step-icon pink\">\u25C6</b><h3>Choose Ticket / Seat</h3><p>Select your ticket and seat when applicable.</p></article>\n      <article><span class=\"step-number\">3</span><b class=\"step-icon green\">P</b><i>Optional</i><h3>Reserve Parking</h3><p>Add a parking slot if you need one.</p></article>\n      <article><span class=\"step-number\">4</span><b class=\"step-icon blue\">\u25A3</b><h3>Pay & Get QR</h3><p>Complete your booking and receive your QR ticket.</p></article>\n    </div>\n  </section>\n\n  <section class=\"parking-feature shell\" id=\"parking\">\n    <div class=\"parking-photo\"><span>PARK<br>SMART.<br><em>EVENT<br>HAPPIER.</em></span></div>\n    <div class=\"parking-copy\"><span class=\"smart-pill\">\uD83D\uDE98 Smart Event Parking</span><h2>Your parking spot can be ready before you arrive.</h2><p>See available parking for your event, select a slot, and keep your parking details together with your booking.</p><ul><li>Live slot availability</li><li>Clear parking zones</li><li>Optional during booking</li><li>One booking, ticket + parking</li></ul><a class=\"btn btn-primary\" href=\"#how\">See How Parking Works \u2192</a></div>\n    <div class=\"parking-map\">\n      @for (slot of ['A01','A02','CAR','B26','B27','B28','C10','C11','C12']; track slot) { <button type=\"button\" [class.selected]=\"slot === 'B27'\" [class.busy]=\"slot === 'B28' || slot === 'CAR'\">{{ slot === 'CAR' ? '\uD83D\uDE99' : slot }}<small>{{ slot === 'B27' ? '\u2713' : '' }}</small></button> }\n      <div class=\"parking-legend\"><span>\u25CF Available</span><span>\u25CF Selected</span><span>\u25CF Occupied</span></div>\n    </div>\n  </section>\n\n  <section class=\"section shell roles\" id=\"roles\">\n    <div class=\"section-head\"><div><h2>Built for <em>Everyone</em></h2><p>Different roles, one seamless platform.</p></div></div>\n    <div class=\"role-grid\">\n      <article class=\"featured\"><span class=\"role-icon\">\u265F</span><div><h3>Customer</h3><p>Discover events, reserve tickets, seats and parking.</p></div><button class=\"btn btn-primary\">Create Customer Account \u2192</button></article>\n      <article><span class=\"role-icon pink\">\u265F</span><div><h3>Organizer</h3><p>Create events, configure tickets, seats and parking.</p></div><button class=\"btn btn-soft\">Organizer Login \u2192</button></article>\n      <article><span class=\"role-icon blue\">\u2699</span><div><h3>Admin</h3><p>Manage events, approvals, bookings and activity.</p></div><button class=\"btn btn-soft\">Admin Login \u2192</button></article>\n    </div>\n  </section>\n\n  <section class=\"stats shell\"><article><b>\u265F</b><span><strong>10,000+</strong><small>Happy Customers</small></span></article><article><b>\u25A3</b><span><strong>500+</strong><small>Events Hosted</small></span></article><article><b>\uD83D\uDE98</b><span><strong>3,000+</strong><small>Parking Slots</small></span></article><article><b>\u2605</b><span><strong>4.8/5</strong><small>User Satisfaction</small></span></article></section>\n\n  <section class=\"final-cta shell\"><div><h2>Your Next Event Starts Here.</h2><p>Find an event, book your seat and arrive with confidence.</p><a class=\"btn btn-white\" href=\"#events\">Explore Events \u2192</a><button class=\"btn btn-outline\" type=\"button\">Create Free Account</button></div><span>Live Events.<br>Better Together.</span></section>\n</main>\n\n<footer id=\"footer\">\n  <div class=\"footer-grid shell\">\n    <div><a class=\"brand\" href=\"#home\"><span class=\"brand-mark\">\u2726</span><span><strong>Eventora</strong><small>Events \u2022 Tickets \u2022 Parking</small></span></a><p>Your complete event and parking reservation platform. Simple. Secure. Reliable.</p><div class=\"socials\">f\u3000\u25CE\u3000\uD835\uDD4F\u3000\u25B6\u3000in</div></div>\n    <div><h3>Explore</h3><a href=\"#events\">Events</a><a href=\"#events\">Categories</a><a href=\"#parking\">Parking</a><a href=\"#events\">Venues</a></div>\n    <div><h3>Account</h3><a routerLink=\"/login\">Login</a><a href=\"#home\">Register</a><a href=\"#events\">My Bookings</a><a href=\"#parking\">My Parking</a></div>\n    <div><h3>Support</h3><a href=\"#footer\">Help Center</a><a href=\"#footer\">Contact Us</a><a href=\"#footer\">FAQ</a><a href=\"#footer\">Live Chat</a></div>\n    <div><h3>Legal</h3><a href=\"#footer\">Privacy Policy</a><a href=\"#footer\">Terms & Conditions</a><a href=\"#footer\">Cookie Policy</a><a href=\"#footer\">Refund Policy</a></div>\n  </div>\n  <div class=\"footer-bottom shell\"><span>\u00A9 2026 Eventora. All rights reserved.</span><span>Made with <b>\u2665</b> for better events</span></div><a class=\"back-top\" href=\"#home\" aria-label=\"Back to top\">\u2191</a>\n</footer>\n", styles: [":host { --ink:#10163e; --muted:#66708c; --purple:#6d28e8; --green:#13a768; display:block; overflow:hidden; }\n.shell { width:min(1120px,calc(100% - 40px)); margin-inline:auto; }\n.hero { min-height:500px; color:#fff; position:relative; background-image:linear-gradient(90deg,rgba(5,18,52,.98) 0%,rgba(6,16,49,.92) 33%,rgba(11,21,66,.3) 65%,rgba(7,18,56,.35)),url('/assets/concert-hero.webp'); background-size:cover; background-position:center; isolation:isolate; }\n.hero::after { content:''; position:absolute; inset:auto 0 0; height:80px; background:linear-gradient(177deg,transparent 48%,#fbfcff 49%); z-index:-1; }\n.nav { height:74px; display:flex; align-items:center; justify-content:space-between; gap:26px; }\n.brand { display:inline-flex; align-items:center; gap:11px; text-decoration:none; min-width:180px; }\n.brand-mark { font-size:42px; line-height:1; transform:rotate(14deg); display:inline-block; }\n.brand strong { font-size:21px; display:block; letter-spacing:-.4px; }.brand small { display:block; font-size:10px; opacity:.8; margin-top:-1px; }\n.nav-links { display:flex; gap:28px; align-items:center; margin-left:auto; }.nav-links a { text-decoration:none; font-size:13px; position:relative; padding:26px 0; }.nav-links .active { color:#c88dff; }.nav-links .active::after { content:''; position:absolute; height:2px; inset:auto 0 17px; background:#b868ff; }\n.nav-actions { display:flex; gap:12px; align-items:center; }.btn { border:0; border-radius:9px; padding:11px 21px; font-weight:700; font-size:13px; cursor:pointer; text-decoration:none; display:inline-flex; align-items:center; justify-content:center; gap:10px; transition:transform .2s,box-shadow .2s,background .2s; }.btn:hover { transform:translateY(-2px); }.btn-primary { color:#fff; background:linear-gradient(135deg,#8549ff,#5f20dd); box-shadow:0 8px 24px rgba(91,35,221,.28); }.btn-white { color:#292164; background:#fff; }.btn-outline { background:rgba(19,25,66,.18); color:#fff; border:1px solid rgba(255,255,255,.7); }.btn-soft { color:#342680; background:#fff; border:1px solid #d8ddef; }.icon-button { width:34px; height:34px; border:0; color:#fff; background:transparent; font-size:28px; cursor:pointer; }.menu-toggle { display:none; color:#fff; border:0; background:transparent; font-size:25px; }\n.hero-content { min-height:390px; display:grid; grid-template-columns:1.22fr 1fr 150px; align-items:center; gap:34px; padding-bottom:78px; }\n.hero-copy { max-width:480px; }.eyebrow { display:inline-block; background:#fff; color:#4335a2; border-radius:999px; padding:7px 16px; font-size:12px; font-weight:700; margin-bottom:14px; }.hero h1 { font-size:clamp(37px,4vw,53px); line-height:1.03; letter-spacing:-2px; margin:0 0 13px; }.hero h1 em,h2 em { font-style:normal; color:#9c59ff; }.hero-copy>p { font-size:15px; line-height:1.55; max-width:500px; margin:0 0 16px; color:#ecedfa; }.hero-buttons { display:flex; gap:15px; margin-bottom:16px; }.btn-large { min-width:150px; padding:13px 23px; }.trust-row { display:flex; gap:22px; font-size:10px; }.trust-row span { color:#e9ecf9; }\n.booking-preview { transform:translateY(8px); }.preview-card { color:var(--ink); background:rgba(255,255,255,.95); border-radius:11px; padding:13px; display:flex; gap:11px; align-items:flex-start; box-shadow:0 16px 35px rgba(6,12,54,.24); }.preview-card div { flex:1; min-width:0; }.preview-card small,.preview-card span { display:block; font-size:9px; color:#59637f; }.preview-card strong { display:block; font-size:13px; margin:2px 0 5px; }.preview-card>b { border-radius:50%; background:#e9e0ff; color:#6c28e7; padding:6px 9px; align-self:center; }.preview-icon { flex:0 0 30px; height:30px; border-radius:7px; display:grid!important; place-items:center; color:#fff!important; font-size:16px!important; }.pink { background:#ee4d8d!important; color:#fff!important; }.violet { background:#7a42ef!important; }.green { background:#16a86c!important; color:#fff!important; }.blue { background:#2081e8!important; color:#fff!important; }.preview-pair { display:grid; grid-template-columns:1fr 1fr; gap:9px; margin-top:9px; }.preview-card i { font-style:normal; display:inline-block; font-size:9px; color:#138553; background:#c9f4dc; padding:4px 8px; border-radius:999px; }\n.ticket-phone { width:132px; height:250px; transform:rotate(7deg); border:7px solid #121941; border-radius:23px; background:linear-gradient(#7751dc 0 38px,#fff 38px); padding:13px 12px; color:#141844; text-align:center; box-shadow:0 22px 55px #050a2e; }.ticket-phone small { display:block; color:#fff; margin-bottom:28px; font-size:9px; }.ticket-phone strong { display:block; font-size:9px; margin-top:10px; }.ticket-phone span { font-size:8px; color:#5e6682; }.qr-pattern { width:72px; height:72px; margin:auto; border:5px solid #fff; background:repeating-conic-gradient(#0e123e 0 25%,#fff 0 50%) 0/14px 14px; box-shadow:inset 0 0 0 2px #fff; }\n.search-wrap { margin-top:-47px; position:relative; z-index:4; background:#fff; border:1px solid #e5e8f3; border-radius:16px; padding:18px 20px 13px; box-shadow:0 18px 40px rgba(53,63,111,.16); }.search-grid { display:grid; grid-template-columns:1.6fr 1.12fr 1.12fr 1.1fr .82fr; gap:10px; }.search-field,.select-field { min-width:0; height:50px; border:1px solid #dfe4f2; border-radius:10px; display:grid; align-items:center; background:#fff; }.search-field { grid-template-columns:36px 1fr; padding:0 10px; }.search-field>span,.select-field>span { color:#682fe9; font-size:24px; }.search-field input { border:0; outline:0; min-width:0; font-size:11px; }.select-field { grid-template-columns:32px 1fr; grid-template-rows:20px 20px; padding:5px 9px; }.select-field>span { grid-row:1/3; }.select-field small { color:#273052; font-size:9px; align-self:end; }.select-field select { border:0; outline:0; min-width:0; color:#626b87; font-size:9px; background:transparent; }.find-btn { height:50px; }.category-row { display:flex; justify-content:center; align-items:center; gap:8px; margin-top:12px; font-size:9px; }.category-row button { border:0; border-radius:999px; min-width:90px; padding:7px 12px; color:#2b3470; background:#edf2ff; cursor:pointer; }.category-row button:nth-of-type(1),.category-row button:nth-of-type(5){background:#f0ddff}.category-row button:nth-of-type(2){background:#d9f4e7}.category-row button:nth-of-type(4){background:#ffe9dd}\n.section { padding-top:22px; }.section-head { display:flex; justify-content:space-between; align-items:end; margin-bottom:12px; }.section-head h2 { margin:0; font-size:26px; line-height:1.1; letter-spacing:-.7px; }.section-head p { margin:4px 0 0; color:var(--muted); font-size:12px; }.section-head a { color:#6125db; text-decoration:none; font-size:12px; font-weight:700; }.search-message { margin:-3px 0 10px; color:#6030d4; font-size:12px; font-weight:700; }.event-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:16px; }.event-card { background:#fff; border-radius:11px; overflow:hidden; box-shadow:0 9px 25px rgba(42,55,105,.12); }.event-image { height:123px; position:relative; background-image:url('/assets/event-grid.png'); background-size:400% 100%; }.date-badge { position:absolute; top:11px; left:11px; width:40px; height:45px; border-radius:7px; background:#fff; display:grid; place-items:center; align-content:center; font-size:8px; color:#3f3298; font-weight:700; line-height:1.1; }.date-badge b { font-size:18px; }.heart { position:absolute; top:8px; right:9px; width:30px; height:30px; border:0; color:#fff; background:rgba(5,13,45,.5); font-size:24px; line-height:1; border-radius:50%; cursor:pointer; }.heart.saved { color:#ff4c83; background:#fff; }.category-badge { position:absolute; bottom:8px; left:10px; padding:4px 10px; border-radius:999px; color:#fff; background:#3a69e9; font-size:9px; }.event-body { padding:10px 13px 11px; }.event-body h3 { margin:0 0 7px; font-size:14px; }.event-body p { margin:4px 0; color:#66708b; font-size:10px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }.event-body>div { display:flex; align-items:end; justify-content:space-between; margin-top:5px; font-size:10px; }.event-body>div strong { font-size:14px; }.event-body small { padding:5px 7px; border-radius:6px; color:#312478; background:#e5e3ff; font-size:8px; font-weight:700; }.empty-state { grid-column:1/-1; padding:35px; text-align:center; color:var(--muted); background:#fff; border-radius:12px; }\n.how { padding-top:21px; }.steps { display:grid; grid-template-columns:repeat(4,1fr); gap:44px; }.steps article { position:relative; padding-left:52px; min-height:78px; }.steps article:not(:last-child)::after { content:''; position:absolute; top:21px; left:calc(100% + 3px); width:40px; border-top:1px dashed #b9c6ed; }.step-number { position:absolute; left:0; top:12px; width:23px; height:23px; display:grid; place-items:center; color:#fff; background:#6427df; border-radius:50%; font-size:10px; }.step-icon { width:43px; height:43px; display:grid; place-items:center; border-radius:50%; background:#eee9ff; color:#6329dc; font-size:24px; margin-bottom:5px; }.steps h3 { font-size:13px; margin:0 0 3px; }.steps p { color:var(--muted); font-size:10px; margin:0; line-height:1.3; }.steps i { position:absolute; top:13px; right:0; font-style:normal; color:#19885b; background:#d8f5e6; font-size:8px; padding:4px 10px; border-radius:999px; }\n.parking-feature { min-height:285px; margin-top:24px; display:grid; grid-template-columns:1.35fr 1.1fr .92fr; background:#fff; border:1px solid #e7e9f3; border-radius:13px; overflow:hidden; box-shadow:0 10px 30px rgba(39,49,98,.1); }.parking-photo { min-height:285px; padding:55px 35px; display:flex; align-items:center; color:#fff; background:linear-gradient(90deg,rgba(21,26,80,.76),rgba(21,26,80,.08)),url('/assets/smart-parking.png') center/cover; }.parking-photo span { font-size:28px; font-weight:800; line-height:.95; }.parking-photo em { font-style:normal; color:#b888ff; }.parking-copy { padding:22px 18px; align-self:center; }.smart-pill { color:#167c54; background:#d8f5e7; border-radius:999px; padding:5px 10px; font-size:9px; }.parking-copy h2 { margin:10px 0 7px; font-size:20px; line-height:1.05; }.parking-copy p,.parking-copy li { color:var(--muted); font-size:10px; line-height:1.4; }.parking-copy ul { padding:0; list-style:none; margin:8px 0 12px; }.parking-copy li::before { content:'\u2713'; color:#fff; background:#10a568; border-radius:50%; padding:0 3px; margin-right:8px; }.parking-copy .btn { padding:10px 17px; }.parking-map { margin:12px; padding:10px; border:1px solid #e4e8f1; background:#f8faff; border-radius:11px; display:grid; grid-template-columns:repeat(3,1fr); gap:8px; }.parking-map button { min-height:56px; border:0; border-radius:7px; background:#e6ebf4; color:#27304f; font-size:9px; }.parking-map button.selected { color:#fff; background:#13bf77; box-shadow:0 7px 18px rgba(19,191,119,.35); }.parking-map button.busy { background:#f7dbe3; }.parking-map button small { display:block; font-size:12px; }.parking-legend { grid-column:1/-1; display:flex; justify-content:space-around; font-size:7px; color:#65708a; }.parking-legend span:nth-child(2){color:#10a76a}.parking-legend span:nth-child(3){color:#e7476d}\n.roles { padding-top:22px; }.role-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-left:310px; margin-top:-44px; }.role-grid article { min-height:116px; padding:12px; border-radius:11px; background:#fff; box-shadow:0 8px 24px rgba(47,61,109,.1); display:grid; grid-template-columns:45px 1fr; gap:10px; }.role-grid article.featured { border:1.5px solid #8c4cff; }.role-icon { width:42px; height:42px; display:grid; place-items:center; border-radius:10px; color:#6930dc; background:#e9ddff; font-size:23px; }.role-grid h3 { margin:2px 0 1px; font-size:13px; }.role-grid p { margin:0; color:var(--muted); font-size:9px; line-height:1.2; }.role-grid .btn { grid-column:1/-1; padding:7px; font-size:9px; }.stats { margin-top:16px; padding:11px 24px; border-radius:10px; background:linear-gradient(90deg,#f1ecff,#f8fbff,#fff2e9); display:grid; grid-template-columns:repeat(4,1fr); }.stats article { display:flex; align-items:center; justify-content:center; gap:12px; border-right:1px solid #dfe5f2; }.stats article:last-child { border:0; }.stats b { font-size:22px; color:#6530db; }.stats strong,.stats small { display:block; }.stats strong { font-size:15px; }.stats small { font-size:8px; color:var(--muted); }\n.final-cta { min-height:138px; margin-top:17px; margin-bottom:14px; padding:28px 38px; border-radius:12px; color:#fff; background:linear-gradient(90deg,rgba(52,25,143,.93),rgba(73,35,172,.63),rgba(56,27,135,.5)),url('/assets/concert-hero.png') center 70%/cover; display:flex; justify-content:space-between; align-items:center; }.final-cta h2 { margin:0 0 4px; font-size:27px; }.final-cta p { margin:0 0 12px; font-size:12px; }.final-cta .btn { padding:10px 18px; margin-right:10px; }.final-cta>span { font-size:21px; font-style:italic; transform:rotate(-6deg); }\nfooter { color:#fff; background:radial-gradient(circle at 70% 0,#10295f,#07172f 55%,#071329); padding:28px 0 12px; position:relative; }.footer-grid { display:grid; grid-template-columns:1.7fr repeat(4,1fr); gap:48px; }.footer-grid .brand { margin-bottom:12px; }.footer-grid p { color:#b8c2d8; font-size:9px; line-height:1.5; max-width:230px; }.socials { margin-top:12px; font-size:15px; }.footer-grid h3 { font-size:11px; margin:5px 0 11px; }.footer-grid>div>a:not(.brand) { color:#b8c2d8; text-decoration:none; font-size:9px; display:block; margin:7px 0; }.footer-bottom { margin-top:22px; display:flex; justify-content:space-between; color:#aab6ce; font-size:8px; }.footer-bottom b { color:#f14873; }.back-top { position:absolute; right:25px; bottom:26px; width:34px; height:34px; border-radius:50%; color:#fff; background:#6d2cea; display:grid; place-items:center; text-decoration:none; }\n@media (max-width:960px) { .nav-links{gap:15px}.nav-links a{font-size:11px}.nav-actions .btn{display:none}.hero-content{grid-template-columns:1fr .9fr}.ticket-phone{display:none}.search-grid{grid-template-columns:1.5fr 1fr 1fr}.search-grid>:nth-child(4){grid-column:1/2}.find-btn{grid-column:2/4}.category-row{flex-wrap:wrap}.event-grid{grid-template-columns:repeat(2,1fr)}.steps{grid-template-columns:repeat(2,1fr);row-gap:25px}.steps article::after{display:none}.parking-feature{grid-template-columns:1fr 1fr}.parking-map{grid-column:1/-1}.role-grid{margin-left:0;margin-top:0}.footer-grid{grid-template-columns:1.5fr repeat(2,1fr)}.footer-grid>div:nth-child(4),.footer-grid>div:nth-child(5){display:none} }\n@media (max-width:700px) { .shell{width:min(100% - 24px,1120px)}.nav{height:64px}.menu-toggle{display:block;order:3}.nav-links{display:none;position:absolute;top:62px;left:12px;right:12px;z-index:9;flex-direction:column;align-items:stretch;gap:0;padding:10px 18px;border-radius:12px;background:#0d1840}.nav-links.open{display:flex}.nav-links a{padding:11px}.nav-links .active::after{display:none}.nav-actions{margin-left:auto}.hero{min-height:640px}.hero-content{display:block;padding-top:35px}.hero h1{font-size:40px}.booking-preview{margin-top:28px;max-width:430px}.trust-row{gap:10px;flex-wrap:wrap}.search-wrap{margin-top:-44px}.search-grid{grid-template-columns:1fr 1fr}.search-field{grid-column:1/-1}.find-btn{grid-column:1/-1}.category-row strong{width:100%;text-align:center}.category-row button{min-width:auto}.section-head h2{font-size:22px}.event-grid{grid-template-columns:1fr}.event-image{height:180px}.steps{grid-template-columns:1fr}.parking-feature{grid-template-columns:1fr}.parking-photo{min-height:230px}.role-grid{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr;gap:12px}.stats article:nth-child(2){border-right:0}.final-cta{padding:24px}.final-cta>span{display:none}.footer-grid{grid-template-columns:1.4fr 1fr;gap:25px}.footer-grid>div:nth-child(3){display:none} }\n@media (max-width:440px) { .brand{min-width:0}.brand-mark{font-size:34px}.brand strong{font-size:18px}.icon-button{display:none}.hero{min-height:665px}.hero h1{font-size:35px}.preview-pair{grid-template-columns:1fr}.booking-preview .upcoming{display:none}.search-grid{grid-template-columns:1fr}.search-grid>*{grid-column:1!important}.select-field:nth-of-type(4){display:none}.event-image{height:155px}.parking-copy{padding:22px}.footer-grid{grid-template-columns:1fr 1fr}.footer-grid>div:first-child{grid-column:1/-1}.footer-bottom{gap:20px}.final-cta h2{font-size:23px} }\n\n/* Readability pass: keep the reference aesthetic without sacrificing user comfort. */\n.nav-links a { font-size:14px; }\n.eyebrow { font-size:14px; }\n.hero-copy>p { font-size:17px; }\n.trust-row { font-size:12px; }\n.preview-card { padding:15px; }\n.preview-card small,.preview-card span { font-size:12px; line-height:1.35; }\n.preview-card strong { font-size:16px; }\n.preview-card i { font-size:11px; }\n.search-field,.select-field,.find-btn { height:58px; }\n.search-field input { font-size:14px; }\n.select-field { grid-template-rows:23px 23px; }\n.select-field small { font-size:12px; }\n.select-field select { font-size:12px; }\n.category-row { font-size:12px; }\n.category-row button { font-size:12px; padding:8px 14px; }\n.section-head p { font-size:15px; }\n.section-head a { font-size:14px; }\n.event-image { height:180px; background-size:400% auto; background-repeat:no-repeat; background-color:#11183f; }\n.event-body { padding:14px 15px 15px; }\n.event-body h3 { font-size:18px; margin-bottom:9px; }\n.event-body p { font-size:14px; margin:7px 0; }\n.event-body>div { font-size:13px; margin-top:8px; }\n.event-body>div strong { font-size:18px; }\n.event-body small { font-size:11px; }\n.date-badge { width:46px; height:52px; font-size:10px; }\n.date-badge b { font-size:20px; }\n.category-badge { font-size:11px; }\n.steps { margin-top:18px; }\n.steps article { min-height:110px; }\n.steps h3 { font-size:16px; }\n.steps p { font-size:14px; line-height:1.45; }\n.steps i { font-size:11px; }\n.parking-feature { min-height:335px; }\n.parking-photo { min-height:335px; }\n.smart-pill { font-size:12px; }\n.parking-copy h2 { font-size:24px; line-height:1.12; }\n.parking-copy p,.parking-copy li { font-size:14px; line-height:1.5; }\n.parking-map button { font-size:12px; }\n.parking-legend { font-size:10px; }\n.role-grid article { min-height:158px; padding:16px; }\n.role-grid h3 { font-size:17px; }\n.role-grid p { font-size:14px; line-height:1.4; }\n.role-grid .btn { font-size:12px; }\n.stats { padding-block:16px; }\n.stats strong { font-size:18px; }\n.stats small { font-size:12px; }\n.final-cta p { font-size:15px; }\n.footer-grid p { font-size:13px; }\n.footer-grid h3 { font-size:15px; }\n.footer-grid>div>a:not(.brand) { font-size:13px; margin:10px 0; }\n.footer-bottom { font-size:12px; }\n\n@media (max-width:960px) {\n  .nav-links a { font-size:12px; }\n  .role-grid { margin-top:0; }\n}\n@media (max-width:700px) {\n  .hero-copy>p { font-size:16px; }\n  .event-image { height:240px; }\n  .steps article { min-height:96px; }\n  .footer-grid>div>a:not(.brand) { font-size:14px; }\n}\n\n.event-image { background-image:url('/assets/event-grid.webp'); }\n.parking-photo { background-image:linear-gradient(90deg,rgba(21,26,80,.76),rgba(21,26,80,.08)),url('/assets/smart-parking.webp'); }\n.final-cta { background-image:linear-gradient(90deg,rgba(52,25,143,.93),rgba(73,35,172,.63),rgba(56,27,135,.5)),url('/assets/concert-hero.webp'); }\n"] }]
    }], null, null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(Landing, { className: "Landing", filePath: "src/app/pages/landing/landing.ts", lineNumber: 23 }); })();
